### ISSUE TITLE
Error while replacing locomotives, train schedule is nil

### ISSUE THREAD

**Issue by LovelySanta** [robot256/MultipleUnitTrainControl#10]
I am still trying to get it working, but I create my whole train first before giving it a schedule... As 2 locomotives with oposite loco's are build, without being the full train (for example, it's still missing some wagons) it's giving this error: 
![image](https://user-images.githubusercontent.com/26593477/62162780-43873700-b319-11e9-9d9f-af604fe1cad5.png)
as the train schedule isn't set yet...

I can reproduce this in vanilla: place a locomotive on the tracks, place a 2nd one in the other direction to it, it won't have a schedule set and create the same error.

**Comment by robot256** [comment]
They fixed the bug in the train schedule API, and revealed a bug in my workaround for the previous bug.  Should be fixed in mod version 0.1.18.
