### ISSUE TITLE
[0.2.4] Crash when placing a train blueprint with fuel in the map editor

### ISSUE THREAD

**Issue by raiguard** [robot256/MultipleUnitTrainControl#12]
A bit long-winded, but that's basically it. Using the editor to insta-place a blueprint with trains, when at least one of those trains has fuel in the blueprint, causes a crash:

![image](https://user-images.githubusercontent.com/3515394/85093150-adfecb00-b1a8-11ea-8a75-db19ce8087af.png)

Here is a blueprint string that causes the crash:

```
0eNqVlFtuwyAQRfcy38QyGD/qrURR5TjTFAmDBTiqZXnvBVtKqzZRp58wc8+dB2KBs55wdMoEaBdQvTUe2uMCXl1Np9NdmEeEFlTAARiYbkgn1ykNKwNlLvgBLV/ZnxJtezvYoG74TSjWEwM0QQWFu/F2mF/NNJzRRfIjPYPR+iixJrlFzEFmsiy4KBnM0OaRb52KpG7PybM6RlI5PgnM1Gvs3OFtQp1KSMX/sBV3Wx9ir9f3cNha/u3c3C0vymG/h8QDZEFGVlSkJCMlFVmSkYKKrEgrFFkpq6Z+ukHxzw3W1EZyah8NlUiezAuVSF4fz6nIJ4/stE856r8+BgY3dH5LqOuC8zJvZMPX9RP2fWa2
```

#### To reproduce

1. Create a new world
2. Enter /editor
3. Import the blueprint string above
4. Attempt to place it
5. See crash

The mod is fantastic, thank you for making it!

**Comment by robot256** [comment]
I just tried to replicate this in 1.0 and it did not crash.  Do you think they fixed something in 1.0?

What I see is, in editor mode time is stopped.  Placing the blueprint creates normal locomotives with fuel in them, as well as the item-request-proxies.  As soon as I exit editor mode, the proxies disappear and the locomotives are replaced with MU locomotives containing the correct fuel.

**Comment by raiguard** [comment]
When I tested it, the editor was unpaused. Press `Numpad0` to unpause it or do it in the time editor. I forgot that it's paused by default since I changed that setting.

**Comment by robot256** [comment]
I replicated the crash, and found that it's because somehow it's trying to create an item-request-proxy with an empty "modules" parameter.  I'm guessing that somehow the editor is autoplacing the fuel in the locomotive and removing it from the request, but not deleting the request entity before MU control finds it.  I will push the fix to robot256lib so that empty item-request-proxies are ignored.  Thanks for the report!
