### ISSUE TITLE
moving_trains can grow without bound, leading to large save sizes

### ISSUE THREAD

**Issue by Xcelled** [robot256/MultipleUnitTrainControl#13]
I'm running this mod in a rail-world playthough in conjunction with https://mods.factorio.com/mod/RenaiTransportation. Renai works by continually dismantling and reassembling trains in motion.

After ~80 hours, I noticed that autosaves were taking upwards of 10 seconds, despite the map not being all that large (and not much larger than at, say, 40 hours). I cracked open the save file and found script.dat was 16 mb. Nearly all of that belonged to MU. Confirmed that removing MU from the playthough brought the script.dat and save times down significantly.

I then cloned the code for MU and had it log the globals table when it loaded the save.

This is what I found:

```lua
  created_trains = {
  -- a reasonable number, but too many to show here 
  },
  downgrade_pairs = {
    ["farl-mu"] = "farl",
    ["locomotive-mu"] = "locomotive",
    ["ret-electric-locomotive-mk2-mu"] = "ret-electric-locomotive-mk2",
    ["ret-electric-locomotive-mu"] = "ret-electric-locomotive",
    ["ret-modular-locomotive-mu"] = "ret-modular-locomotive"
  },
  inventories_to_balance = {},
  moving_trains = {
    [46] = {
    },
    [47] = {
    },
    [48] = {
    },
   -- On...
  -- and on... :joy:
  -- and on...  until
    [430752] = {
    }
  }
```

The table took up 500,000-some odd lines :open_mouth:

My gut feeling after a quick glance through the code is that there are two problems at work here. First is that Renai doesn't raise a destroy event when removing a train. The second is that MU doesn't listen for destroy events, or take other actions to clean out the moving_trains besides assuming they eventually stop moving.

Granted, this is kind of an extreme case of trains being destroyed, but it's probably worth fixing. My quick 'n dirty approach would be to add a handler to `script_raised_destroy` which removes trains on destroy. I'd also add a timer (5 minutes or something) that would check moving trains to make sure they're still valid. This is an extra safety measure in case, like Renai, a mod doesn't raise a destroy event.

I'm going to send a PR to Renai to raise the destroy events.

**Comment by robot256** [comment]
Thanks for finding an actual bug!  You are right, my code totally assumes that any moving train will eventually come to a stop totally intact.  It would have the same problems if a locomotive is destroyed by biters, etc.

It sounds like the on_train_created event is still triggering just fine on Renais stuff.  Most of the defunct train IDs will be cleared if I add code on that event to purge the two "previous" train IDs from the "moving" list.  The script_raised_destroy event would only be needed to catch single-unit trains that get destroyed.

**Comment by Xcelled** [comment]
By previous, do you mean numerically previous (like, `<new train id > - 1`)? That might not be safe, as long trains can take a very long time to go off a ramp, especially if starting from a stop. In the meantime, other trains could go off of other ramps (and be reformed).

Fwiw, I hacked in some code to clear the dead trains out of my local save and it reported that it cleared out something like 192,000 trains. I can provide the save if you want it for testing purposes instead of generating your own 80-hour map :sweat_smile:

**Comment by robot256** [comment]
The on_train_created event actually contains between 1 and 3 train IDs. The 2nd and 3rd, if they exist, are the IDs of old trains that were joined or split to produce the 1st (the new one). So you automatically know that 2nd and 3rd don't exist anymore.

When I push the update, I'll add scrubbing the list to the migrations script.  Having your save would be helpful for testing.

**Comment by robot256** [comment]
Hmm.  Doing some tests, the "old_train_id" check doesn't catch everything, even on normal jumps.  (This mod is wacky, BTW!)  I think you're right, and moving_trains needs to be purged periodically all the time.

**Comment by Xcelled** [comment]
Did not know that about the train created event, cool!

Now I just have to figure out how to upload a 20mb save file :sweat_smile:

**Comment by Xcelled** [comment]
I always forget about Google Drive... https://drive.google.com/file/d/1cBF5iKHKH5njI3MGO4zJlLEJaBq5m9GM/view?usp=sharing

**Comment by robot256** [comment]
Fixed in the latest version on the mod portal!  It does both the old_train purges and the time-based purges.  Applied to your save (with debug prints enabled just after loading) you can see 195366 entries purged on the first cycle.  After that, there are a handful every minute as the trains make their jumps.

![purged 195339 trains](https://user-images.githubusercontent.com/14794356/99153730-7c672e80-2678-11eb-98de-08d165691ea4.jpg)

**Comment by Xcelled** [comment]
Thank you! :heart:
