### ISSUE TITLE
Trains go... spinny?

### ISSUE THREAD

**Issue by Xcelled** [robot256/MultipleUnitTrainControl#14]
This is one of the more baffling bugs I've ever encountered, so I'll just show it:

![spinnies-slow](https://user-images.githubusercontent.com/5599341/99450227-74182900-28ee-11eb-8c29-547afbd13416.GIF)

While I admit that it looks kick-ass, it does unfortunately result in the train breaking apart :( Usually I'm able to hedge a guess about what the problem might be, but in this instance, I'm just... baffled.

I think I've been able to narrow it down a bit, at least:
- Train must be an MU train. Simple case of back-to-back locos triggers the bug
- Speed seems to be important. Slower speeds don't cause the bug. Nuclear fuel is a must
- It started happening *midway* through a play session yesterday, with no changes to the train. It now always happens given the conditions above are met

One other interesting fact: Some seconds after breakup, MU prints a message about replacing an MU loco with a standard loco, but _only_ for the rear engine. The rear engine is the somewhat ironically named "Exactly what you'd expect".

I know of no code in either this mod or RenaiTransportation that could produce anything even remotely like this, so  I'm not sure where exactly this bug lies, either here or in RenaiTransportation. I'm filing it here because it seems to be specific to MU trains, but I'm going to tag @Kiplacon so they can jump in and look as well.

Full video of the incident above: https://youtu.be/NRLyVL9Zahw

Save file: https://drive.google.com/file/d/1DY3__yJC9KMpeXaf8i4v8R0rM9pegzIo/view?usp=sharing

**Comment by robot256** [comment]
Delightful!  Is the pirouette before landing one of the symptoms of this error?  AFAIK, MU doesn't know the air-trains exist, so I can't see how it would be causing that particular symptom.

Do you know what Train ID your save is up to?  I don't know what the game does if you exceed a 32-bit integer.  I calculated it was not an issue for my Automatic Coupling System bases, but Renai jumps involve many more intermediate train IDs per operation.  It's the only thing (besides mod updates) that I can imagine would trigger something this far into a game.

Does the lead locomotive eventually get replaced by MU when it comes to a stop as well?

**Comment by robot256** [comment]
I have reproduced the bug with MUTC uninstalled, so it appears to be isolated to RenaiTransportation.

https://drive.google.com/file/d/1W1Pa6yDqxjkkBR6DXNU6rkiwwJ4dBWtI/view?usp=sharing

(And it took me a minute to realize you had CAH names installed.  Great idea B-)

**Comment by Xcelled** [comment]
Cool, thanks for the assist!

The first loco isn't ever replaced, so this could be highlighting an edge case in MU by chance.

**Comment by Xcelled** [comment]
Also train IDs shouldn't be a problem, I'm not sure what their exact datatype is but if it's the worst case (signed int), a save could create 1,000 new trains every second and the ID wouldn't roll over for 600 hours of play time.

**Comment by Kiplacon** [comment]
That spinning happens because of the equation used to control the tilt of the train sprite while its in the air. Ideally, the graph of that equation crosses the x-axis (ie y = 0 = no tilt) at the exact calculated tick the train is supposed to land. The spinning will happen if the train takes longer to land than calculated (after crossing the x-axis, the graph dips negative really fast) and that calculation is based on the train's speed. I guess it's possible with nuclear fuel and a high train break speed research that the calculation would get thrown off, that's all I can think of

**Comment by robot256** [comment]
> Cool, thanks for the assist!
> 
> The first loco isn't ever replaced, so this could be highlighting an edge case in MU by chance.

It is replaced, actually, but not until it completes  a massive turnaround loop and comes to a stop.

Yeah, your save is only up to train id 500,000 or so.  Considering I've got a 400-hour game under my belt, I'd shoot for at least 1000 as the limit 😂

**Comment by Xcelled** [comment]
> It is replaced, actually, but not until it completes a massive turnaround loop and comes to a stop.

Whoops, guess I never bothered to wait for it to actually stop lol.

**Comment by Xcelled** [comment]
Closing this one in favor of the issue I opened on Renai-Transportation.
