### ISSUE TITLE
Factorio mods localization helper

### ISSUE THREAD

**Issue by dima74** [robot256/MultipleUnitTrainControl#18]
Hi, thanks for using [factorio-mods-localization](https://github.com/dima74/factorio-mods-localization) helper! Please note that in order for a mod to be imported correctly, it is currently needed that files in any localization folder (such as `/locale/fr`) have the same names as files in `/locale/en` folder. I would recommend to rename [`locale/fr/fr.cfg`](https://github.com/robot256/MultipleUnitTrainControl/blob/976884096ebb6e589e8468628c8c4ed529a4c3aa/locale/fr/fr.cfg) and [`locale/en/en.cfg`](https://github.com/robot256/MultipleUnitTrainControl/blob/976884096ebb6e589e8468628c8c4ed529a4c3aa/locale/en/en.cfg) to something like `locale/fr/locale.cfg` and `locale/en/locale.cfg`. Same for mods `Vehicle-Wagon-2`, `rocket-log` and `shipping-containers`

**Comment by robot256** [comment]
Thank you for the advice and for the plugin!  I think all my mods are standardized on locale.cfg for everything now.
