### ISSUE TITLE
[0.1.15] Error from train destruction

### ISSUE THREAD

**Issue by 0ptera** [robot256/MultipleUnitTrainControl#7]
Destroying trains at random with hive mind mod this error popped up:
```
Error MainLoop.cpp:1166: Exception at tick 115477122: The mod Multiple Unit Train Control caused a non-recoverable error.
Please report this error to the mod author.

Error while running event MultipleUnitTrainControl::on_tick (ID 0)
__MultipleUnitTrainControl__/util/replaceLocomotive.lua:58: attempt to index local 'newLoco' (a nil value)
stack traceback:
	__MultipleUnitTrainControl__/util/replaceLocomotive.lua:58: in function 'replaceLocomotive'
	__MultipleUnitTrainControl__/control.lua:122: in function 'ProcessReplacement'
	__MultipleUnitTrainControl__/control.lua:193: in function 'ProcessTrain'
	__MultipleUnitTrainControl__/control.lua:269: in function 'ProcessTrainQueue'
	__MultipleUnitTrainControl__/control.lua:297: in function <__MultipleUnitTrainControl__/control.lua:294
```

My swarm destroyed several trains at random before this.

Attached complete log:
[factorio-current.log](https://github.com/robot256/MultipleUnitTrainControl/files/3100968/factorio-current.log)

**Comment by robot256** [comment]
It looks like one locomotive of a pair was destroyed, and while MUTC was replacing the other with a standard version, its spot was either blocked or it was destroyed in between the three lines of code where it is destroyed, created, and modified.  Maybe there was a ton of acid splash on the track, or a biter shoved into its spot in that instant?

```
	-- Destroy the old Locomotive so we have space to make the new one
	loco.destroy{raise_destroy=true}
	------------------------------
	-- Create the new locomotive in the same spot and orientation
	local newLoco = surface.create_entity{name=newName, position=position, direction=newDirection, force=force, create_build_effect_smoke=false}
	
	-- Restore coupling state
	if not disconnected_back then
		newLoco.disconnect_rolling_stock(defines.rail_direction.back)
	end
```

The easiest solution is simply to detect when the create_entity call fails, and you will have lost a locomotive.  If it only occurs due to biter swarms, then you would probably have lost it anyway, so not much difference there.  Is there anything else that can be done?

**Comment by 0ptera** [comment]
Does creating in script even do checks against a spot being occupied by a different entity such as biter under locomotive?
Maybe the locomotive destroyed was just slightly over a destroyed piece of rail making it impossible to create a new one in that position.

It might be possible to trigger this in a different, more reproducible manner, but generally it should be fine to have the locomotive simply vanish if the replacement couldn't be built in either direction.
Probably a good idea to write a console error message in this case.

**Comment by robot256** [comment]
I know create_entity can fail and return nil, and suspect train placement works the same as building placement (or else you drop the train on the biter like an [ACME anvil](https://media.giphy.com/media/MxeYM5IduPqms/giphy.gif)?)  I'll add a console message when a replacement fails.
