### ISSUE TITLE
Mod compatibility friendly

### ISSUE THREAD

**Issue by LovelySanta** [robot256/MultipleUnitTrainControl#8]
Hi,

I got a mod that creates trains, but I need to get the events when you replace a locomotive... (it is breaking my mod otherwise).

https://github.com/robot256/MultipleUnitTrainControl/blob/0b6d2bfe86c8811ef1f388db43ef89c3d8afea4d/util/replaceLocomotive.lua#L53-L56

You raise the destroy event, but you don't raise the build event for the new one...
Also, the way you have it now, trains will snap to train stops, instead of placing them on the exact spot they stood in before...

Can you change the code to:
```lua
loco.destroy{raise_destroy=true}

local newLoco = surface.create_entity{
	name = newName,
	position = position,
	direction = newDirection,
	force = force,
	create_build_effect_smoke = false,
	raise_built = true, -- raise build event of new loco
	snap_to_train_stop = false, -- make sure they are build where you deleted the other one
}
```
I think this is the only place where you remove and replace the locomotives?

Kind regards
lovely_santa (a fellow modder)

**Comment by robot256** [comment]
(Copied from my reply in the pull request)
Thanks, I did not know about `snap_to_train_stop`.

My mod should already raise the `script_raised_built` event. It does so manually with a `raise_event` command, so that my script can finish copying all the parameters from the old locomotive before other scripts interrupt it responding to the event:

```lua
    -- Destroy the old Locomotive so we have space to make the new one
	loco.destroy{raise_destroy=true}
	------------------------------
	-- Create the new locomotive in the same spot and orientation
	local newLoco = surface.create_entity{name=newName, position=position, direction=newDirection, force=force, create_build_effect_smoke=false}
	-- make sure it was actually created
	if not newLoco then
		return nil
	end
	
	<snip>	
	
	-- After all that, fire an event so other scripts can reconnect to it
	script.raise_event(defines.events.script_raised_built, {entity = newLoco})
	
	-- Restore the train schedule and mode
	newLoco.train.schedule = train_schedule
	newLoco.train.manual_mode = manual_mode
```

This seems to work for a few other mods who respond to `script_raised_built` events, including Realistic Electric Trains.  Is it not working correctly for you?

**Comment by LovelySanta** [comment]
I'll have a look later, I'll get back to this topic!

**Comment by LovelySanta** [comment]
I am still trying to get it working, but I create my whole train first before giving it a schedule... As 2 locomotives with oposite loco's are build, it's giving this error: 
![image](https://user-images.githubusercontent.com/26593477/62162780-43873700-b319-11e9-9d9f-af604fe1cad5.png)
as the train schedule isn't set yet...

**Comment by LovelySanta** [comment]
I'm still getting this to work together... I must say, the events are indeed firing and I could register the trains correctly, but I cant test this since I got this bug (#10).

As we're still working on mod compatibility, I got some more suggestions:

For your MU trains, you create a dummy recipe that players can't see anyway, as you set it hidden:
https://github.com/robot256/MultipleUnitTrainControl/blob/757227b899510ac55073e2dcd77e7aaccb7e2c68/util/createMuLocoRecipePrototype.lua#L13-L35
#### My suggestion is also setting [`allow_as_intermediate`](https://wiki.factorio.com/Prototype/Recipe#allow_as_intermediate) to false on the recipe, so it doesn't show up as raw ingredient in other recipes:
![image](https://user-images.githubusercontent.com/26593477/62166952-594d2a00-b322-11e9-9efe-4187e9343c61.png)

The recipe might be hidden, as the player crafting inventory is a recipe selection; when selecting an item (for example the constant combinator, or logistics requests) it still shows up as an item:
https://github.com/robot256/MultipleUnitTrainControl/blob/757227b899510ac55073e2dcd77e7aaccb7e2c68/util/createMuLocoItemPrototype.lua#L11-L23
#### Here my suggestion is setting the item [`flags = {"hidden"}`](https://wiki.factorio.com/Prototype/Item#flags) so it is hidden from the player in those menus as well:
![image](https://user-images.githubusercontent.com/26593477/62167082-b517b300-b322-11e9-99a6-8bf2c5d2f17d.png)

**Comment by robot256** [comment]
Thanks for the recipe flag suggestions.  I'll have to look into it more when I get back from a Factorio-free trip (about 3 weeks from now).

**Comment by LovelySanta** [comment]
No problem, I just do it on my end anyway. Just want to show you the result:
```lua
if mods["MultipleUnitTrainControl"] then
  for locomotive,_ in pairs(data.raw["locomotive"]) do
    if string.sub(locomotive, -3) == "-mu" then
      local recipe = data.raw["recipe"][locomotive]
      if recipe then recipe.allow_as_intermediate = false end

      local item = data.raw["item"][locomotive] or data.raw["item-with-entity-data"][locomotive]
      if item then
        item.flags = item.flags or {}
        table.insert(item.flags, "hidden")
      end
    end
  end
end
```

For the recipe, it shows the correct total raw:
![image](https://user-images.githubusercontent.com/26593477/62195253-e1135280-b37b-11e9-9efd-6f5c27323f3e.png)

And for the item, it is hidden as well:
![image](https://user-images.githubusercontent.com/26593477/62195276-ee304180-b37b-11e9-85d3-509717f89a1c.png)

Thanks for the quick fixes!
lovely_santa

**Comment by robot256** [comment]
Finally added these two flags to the base mod.  Thanks!
https://github.com/robot256/MultipleUnitTrainControl/commit/bdee24eca36456463e307408cf3c469926ef9201
